version: '3.9'
services:
  project.users.mongo:
    image: mongo:4.4
    restart: always
    container_name: project.users.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: MONGO_INITDB_DATABASE

    ports:
      - 27017:27017

    volumes:
      - project.mongo.users:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/project-users --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  project.user.mongo.ui:
    image: mongo-express
    restart: always
    container_name: project.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@project.users.mongo:27017/

volumes:
  project.mongo.users:
